### ISSUE TITLE
Heroku Rails console warning

### ISSUE THREAD

**Issue by hdamico** [rootstrap/rs-code-review-metrics#89]
## Description

Currently, we are receiving `Creating scope :open. Overwriting existing method Events::PullRequest.open.` warning on the Heroku rails console, this is because we have `open` inside the state enum which is overwriting `Kernel#Open` method.

### Possible fix

I found this [issue](https://github.com/rails/rails/issues/31234) on GitHub community, which gives us a possible solution, that is putting `class << self; undef_method :open; end` before the enum declaration.

**Comment by santib** [comment]
other solution might be using another name instead of `open`

**Comment by hdamico** [comment]
> other solution might be using another name instead of `open`

Ok! Let's change it to `opened`, I will open a PR
